#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get -y update && apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 775 /var/www
echo 'Hello World!' > /var/www/html/index.hmtl
echo 'Ceci n'est pas une page' >  /var/www/html/404.html
SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
	location /rediret_me {
		return
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}

}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
