#!/usr/bin/env bash
# prints a string 10 times using while loop except the 9th time it should print "HI"

i=0
while ((i < 10)); do
    if [ $i -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done