#!/usr/bin/env bash
# prints a string 10 times using while loop except the 9th time it should print "HI"

i=1
while ((i < 10)); do
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    echo "Best School"
    ((i++))
done